### ISSUE TITLE
Cannot use Hires. fix

### ISSUE THREAD

**Issue by mwbdcz** [ahgsql/StyleSelectorXL#1]
After enabling the StyleSelectorXL plugin, opening (Hires. fix) will report an error.It seems to be caused by not inputting prompt words. 

*** Error completing request
*** Arguments: ('task(kdl6yijpo2wttb3)', '1girl, ', '', [], 20, 18, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 1024, 1024, True, 0.7, 1.1, 'Latent', 20, 0, 0, 0, '', '', [], <gradio.routes.Request object at 0x000001BD0092BAF0>, 0, True, '3D Model', False,

Change the process (self, p, is_enabled, style) in the program to process_ Batch (self, p, is_enabled, style, * * kwargs) can solve problems

**Comment by ahgsql** [comment]
cant reproduce this issue, its working with Hires.Fix with no errors. Can you direct me to get your erros. In which stage or screen you saw that error

**Comment by blacklockshoot** [comment]
i got same problem when i use styleselect with Hires. fix,

TypeError: must be real number, not NoneType

dreamshaperXL checkpoint,
hires step 0 and Denoising strength 0.45
size is 1024 x 1024

if i disable styleselect, all processing with no problem

**Comment by Zibbibbo** [comment]
I have the same problem

**Comment by naql** [comment]
I ran into this error when I first downloaded your extension, then it went away by itself.  THen I updated, I see you have added a bunch of new styles and the error has come back.  Here is the full stack trace:

    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "D:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "D:\stable-diffusion-webui\modules\txt2img.py", line 62, in txt2img
        processed = processing.process_images(p)
      File "D:\stable-diffusion-webui\modules\processing.py", line 677, in process_images
        res = process_images_inner(p)
      File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "D:\stable-diffusion-webui\modules\processing.py", line 783, in process_images_inner
        p.setup_conds()
      File "D:\stable-diffusion-webui\modules\processing.py", line 1204, in setup_conds
        self.calculate_hr_conds()
      File "D:\stable-diffusion-webui\modules\processing.py", line 1187, in calculate_hr_conds
        self.hr_uc = self.get_conds_with_caching(prompt_parser.get_learned_conditioning, self.hr_negative_prompts, self.steps * self.step_multiplier, [self.cached_hr_uc, self.cached_uc], self.hr_extra_network_data)
      File "D:\stable-diffusion-webui\modules\processing.py", line 353, in get_conds_with_caching
        cache[1] = function(shared.sd_model, required_prompts, steps)
      File "D:\stable-diffusion-webui\modules\prompt_parser.py", line 163, in get_learned_conditioning
        conds = model.get_learned_conditioning(texts)
      File "D:\stable-diffusion-webui\modules\sd_models_xl.py", line 24, in get_learned_conditioning
        "original_size_as_tuple": torch.tensor([height, width], **devices_args).repeat(len(batch), 1),
    TypeError: must be real number, not NoneType```

```
For me, I do NOT get this error if it is "Base" selected, but any of the other styles do generate the error.  I did not realize that "Hires-fix" was involved in this.  I tried unchecking that and, sure enough, it did generate and use your style.  As soon as I re-enable Hires-fix, it comes back and cannot generate until your styles are unselected.

**Comment by wardensc2** [comment]
Please fix the issue with Hires Fix, I got the same bug as other people. Thank you in advance

**Comment by mwbdcz** [comment]
Roughly analyze process and process_ Batch is different. Process will only be called once during generation_ Batch is called before each generation. The reason for the error is not difficult to see from the stack trace that the prompt word after '3D Model' is missing, only this title. Hires.fix will be generated twice, but due to the fact that process is only called on the first generation and not called on the second, the prompt words before and after are inconsistent. So reported an error, I am not a professional. But change process() to process_ Batch() after , the problem was indeed resolved

**Comment by eniora** [comment]
Same here when using Hires fix with SDXL 1.0
"TypeError: must be real number, not NoneType"

**Comment by wardensc2** [comment]
> 

Can you describe how to fix manually by editing some files ??

**Comment by ahgsql** [comment]
Tried all of steps, but just couldn't reproduce it.  not sure why, no matter how many times i enable and disable hires, or change styles.

But it seems really annoying, And changing process to process_batch causing another errors thats needs to be fixed for general usage. Any one can fix, please create pull request. I am kinda busy these weeks

**Comment by wardensc2** [comment]
> Tried all of steps, but just couldn't reproduce it. not sure why, no matter how many times i enable and disable hires, or change styles.
> 
> But it seems really annoying, And changing process to process_batch causing another errors thats needs to be fixed for general usage. Any one can fix, please create pull request. I am kinda busy these weeks

Here is my screenshot when using hires fix 

![image](https://github.com/ahgsql/StyleSelectorXL/assets/77379748/58b383d7-8dc4-4656-bd44-867f9bc60d67)

**Comment by naql** [comment]
with the latest, it's no longer blowing up, it's just not doing anything.   uninstalling
