### ISSUE TITLE
An error occurred: No template found with name

### ISSUE THREAD

**Issue by nlienard** [ahgsql/StyleSelectorXL#15]
A1111 1.6

Whenever i use the style editor i got this error

```
An error occurred: No template found with name '['Cinematic', 'Cinematic']'.
An error occurred: No template found with name '['Cinematic', 'Cinematic']'.
*** Error running process: C:\Users\nico\IA\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
    Traceback (most recent call last):
      File "C:\Users\nico\IA\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "C:\Users\nico\IA\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 485, in process
        all_prompts, all_negative_prompts = generate_prompts(
      File "C:\Users\nico\IA\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
        all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
      File "C:\Users\nico\IA\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\randomprompt.py", line 71, in generate
        prompts.append(next(iter(gen)))
    StopIteration

```

Reinstalling the extension didn't change anything

Any clue is welcome. thks

**Comment by nlienard** [comment]
all the style are in doublon in the list:

![image](https://github.com/ahgsql/StyleSelectorXL/assets/13884545/60c0533c-55e1-4547-8706-eb07020cceb9)
